[package]
name = "jtag-taps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libftd2xx = "0.32"
ftdi-mpsse = "0.1"
